### ISSUE TITLE
Adding patterns without stitch between patterns

### ISSUE THREAD

**Issue by cvick32** [EmbroidePy/pyembroidery#126]
I'm pulling in separate font files from the filesystem, and I'd like to keep each letter free from the others so I can modify the placement. Say I want to create a pattern that will spell out "Dog". Currently I do something like this:

`dog = EmbPattern("D.pes")`
`dog.add_pattern("o.pes", dx=500)`
`dog.add_pattern("g.pes", dx=500)`
`dog.write("Dog.pes")`

This works pretty well for a start, but I'm unable to drag the "o" when I pull up `Dog.pes` in PEDesign. 

I've looked around in `EmbPattern.py`, but I couldn't find anything that mentioned no connections between added patterns.

Let me know if there's anything I can do to clarify.

**Comment by tatarize** [comment]
To drag the `o` in PEDesign would require writing the PES in a different fashion. Currently it's written the same way almost all embroidery software writes PES, as a single stand alone block. Because mostly the PES part of the code is only for PEDesign and it's a lot of work to get correct, making fancier stuff to put into the PES so that the PEDesign can act on the CSewSeg blocks as independent things, is generally not something any software does (other than PEDesign itself).

In theory, one could do multiple files in VP3 or multiple CSewSeg blocks within PES but the main goal is to get it working in a useful manner. There's a lot of higher level objects within PES files and it's not a goal to make these objects convert, or to parse them in any meaningful way.

I assume there are methods to split stitches in PEDesign. Those would clearly be the way forward here. Getting the stitches into the sewing machine is the important part for pyembroidery. https://www.youtube.com/watch?v=2QX9AbUdB70 may provide some insight into the tools needed to rectify this.

**Comment by cvick32** [comment]
Ah, I see. 

I watched a few videos on PEDesign, and it looks like there is a tool built-in that will separate out the design into the constituent colors. I was thinking that if I was able to write the joining stitch in a different color than the rest of the design, that might make it easier. 

I also came across this at the end of `add_pattern()` in `EmbPattern.py` that looks to me like it's handling the joining stitch:

```
join_position = len(self.stitches)
self.stitches.extend(pattern.stitches)
for i in range(join_position, len(self.stitches)):             
  data = self.stitches[i][2] &amp; COMMAND_MASK
  if data == STITCH or data == SEW_TO or data == NEEDLE_AT:   
    break            
  elif data == COLOR_CHANGE or data == COLOR_BREAK or data == NEEDLE_SET:  
    self.stitches[i][2] = NO_COMMAND        
self.extras.update(pattern.extras)
```
I know it's not in the scope of the project at large, but I was wondering if you had any idea on how to get started on not writing the joining stitch at all (I'd do this on my own fork). 

Thanks for your help.

**Comment by tatarize** [comment]
You could add in a dummy pattern I'd figure. If the same last color is used in the new patterns first color it will reuse that color. So long as there's a color change it'll be fine.

That code looks to be checking the data and if it consists of a stitch will use that, but if it's one of the break-command types will turn that command into a no-op. 

IF you wanted to add in a dummy stitch you should probably add it in normally. There's no joining stitch, there's a joining color change and removal of the END command and adding in some Matrix Translate stuff. I'd think you'd want to just write any old pattern of a stitch in some identifiable color and then add that to the end of the first pattern or start of the previous pattern.

The ability to handwrite a pattern is fairly well documented. You'd just make that a pattern and add it in.  You might want to avoid adding an extra block to the end if the first loaded pattern since they tend to have END commands and won't necessarily join correctly, without that being removed.

But, you could certainly wrap that one stitch in a different pattern and add it to the first pattern. 

```python
pattern = EmbPattern()
pattern.add_block([(0, 0), (0, 1)], "red")
firstpattern += pattern
firstpattern += secondpattern
```

And that would merge the 3 patterns together. 

If you wanted to just add the block on it's own you'd need to strip the end commands.

```python
 for stitch in pattern.get_match_commands(pyembroidery.END):
  stitch[2] = pyembroidery.NO_COMMAND
pattern.add_block([(0, 0), (0, 1)], "red")
pattern += secondpattern
```

Though your mileage may vary.
