### ISSUE TITLE
Question - Scaling a .PES read / pattern

### ISSUE THREAD

**Issue by stephenk-caa** [EmbroidePy/pyembroidery#152]
Hello there, this module has been very useful in my project and I really appreciate it. If it's not too much trouble I have a question on how scaling works. I'd like to be able to apply a scaling to a read or to future stitches and it seems like it should be possible based on docs.

I tried using the reader settings as suggested in [docs](https://github.com/EmbroidePy/pyembroidery#writing) a couple ways like:
```
self.pattern = pyembroidery.read_pes(pattern_path, {scale: (2, 2)}, self.pattern)
self.pattern = pyembroidery.read_pes(pattern_path, {scale: (50, 50)}, self.pattern)
self.pattern = pyembroidery.read_pes(pattern_path, {scale: 5}, self.pattern)
self.pattern = pyembroidery.read_pes(pattern_path, {scale: 50%}, self.pattern)
```

Then I tried using the middle commands from [docs](https://github.com/EmbroidePy/pyembroidery#middle-level-commands) in an attempt to just explicitly force a scaling:
```
self.pattern.add_command(MATRIX_SCALE, 5, 5)
self.pattern.add_command(MATRIX_SCALE_ORIGIN, 5, 5)
```
but nothing happens

What's weird is MATRIX_TRANSLATE / MATRIX_RESET work fine
```
self.pattern.add_command(MATRIX_TRANSLATE, 30, 30)
```
this actually does translate the reference frame as expected. Am I fundamentally misunderstanding how this works? Is something like this possible? Any response greatly appreciated 👍

**Comment by tatarize** [comment]
Yes, something like that is possible. And it should actually work. It does only apply to future stitches though. So when you apply a scale, it will scale future stitches by that scale amount. Also, there's a weird quirk with the difference between MATRIX_SCALE and MATRIX_SCALE_ORIGIN where I think the SCALE_ORIGIN is much more what you would expect and I think the actual MATRIX_SCALE itself applies to the last point or something so scales everything according to some position or something.

See the discussion: https://github.com/EmbroidePy/pyembroidery/issues/136

**Comment by tatarize** [comment]
Oh, also the scaling stuff will only get applied if it runs through the EmbEncoder but that should be the case for nearly everything. Since the encoder is how that stuff gets applied. See the code at https://github.com/EmbroidePy/pyembroidery/blob/3d0db61e7a08bba8e51f4e5873ebfa678c12960b/pyembroidery/EmbEncoder.py#L345 where it adds this stuff to the matrix which all future points are run through when they are added. This means when the encoder sees this command it adds that to the encoder's matrix then when additional stitches are added those stitches are transformed through that matrix. So the scale must occur before a section to apply to that section.

**Comment by stephenk-caa** [comment]
I got it working properly by adding `MATRIX_SCALE_ORIGIN` command - so many thanks for that.

Also for my future reference, I was also messing this up because of my understanding of what MATRIX referred to. I was trying to scale, but later on using a `MATRIX_RESET` command to reset the reference frame, not knowing that it also reset any scaling that I had applied to the matrix as well.

Appreciate explaining the Encoder because I definitely had that wrong!
