### ISSUE TITLE
png to dst

### ISSUE THREAD

**Issue by sangramrajekakade** [EmbroidePy/pyembroidery#53]

**Comment by sangramrajekakade** [comment]
when i convert dst file to png every time ping color changing how? i am using pyembroidery

**Comment by tatarize** [comment]
The DST files don't have any color data. They are machine instructions for the embroidery machine, as such they have data for stopping the machine, moving to a new location and blocking the needle bar, moving to a new location and not blocking the needle bar. And sequins. But, DST files don't have any color data stored within them, so when you convert from DST to PNG it selects a random set of colors because PNG files have to have a color and the DST files do not have that data.

Here's the technical specs on the format you'll see nothing in them stores that data.
* https://edutechwiki.unige.ch/en/Embroidery_format_DST

There is an option for extended header called "extended header" which you could set to True, but that would be for saving the DST, and would save the color data but would sacrifice compatibility on some embroidery machines. Already made DST files don't have colors in them.

**Comment by wwderw** [comment]
This is why we (digitizers) send out "stitch charts" with DST files.  Because each time those files are opened, it will show a slightly different color.

Even if the file did retain the color info (say PES format), still can manipulate what color is used for what "color" block at the machine.  Color info in of itself is not really set in stone even with files that support origin design color.
