### ISSUE TITLE
Merge two patterns

### ISSUE THREAD

**Issue by styloInt** [EmbroidePy/pyembroidery#60]
I am having trouble merging two pes files. 

The idea is to load them separtly, translate some of them, and then merge them together. 
Is it possible to do that ?

**Comment by tatarize** [comment]
It is possible to do that. But, the thing that's causing an issue is something even I didn't realize right off. I added that doing that to the command line pyemb tool.
https://github.com/EmbroidePy/pyembroidery-CLI

So you can see it done if you have that and do:
`python pyemb.py -i cat.pes -t 300 0 -m duck.pes -o merged.pes`

The non-obvious thing that I must document is that when you load an embroidery the final thing that gets tagged on the end is a command `END`.  This ends the embroidery when the embroidery is processed. Most of the writers too will see and END command and stop writing. The only possible exception is VP3 which technically could string together multiple design patterns in the same file. It's that reason I left it to concatenate patterns like that. If the VP3 writer is expanded to do multi-design single-file that's how the formatting should be.

Before loading the second PES clip the END command from the current stitches.
`pattern.stitches = pattern.stitches[0:-1] `

I will document this cryptic oversight.

**Comment by tatarize** [comment]
Or if you don't want to mess with it while you're busy merging them etc.
```
 for stitch in pattern.get_match_commands(pyembroidery.END):
        stitch[2] = pyembroidery.NO_COMMAND
```

This will find all the `END` stitches and make them `NO_COMMAND` stitches which will then just be ignored during processing. Quirky. And my documentation in the readme implied very strongly that they'd merge without any issue.

Thank you. I've fixed the documentation and made a note. And expanded the CLI tool to permit this kind of operation.

**Comment by styloInt** [comment]
Thank you for your answer and your time. I managed to do what I want. If you don't care about the colors, you just have to do that : 

```
pattern = pyembroidery.read(path, None)
pattern.stitches = pattern.stitches[0:-1]

pattern.move_center_to_origin()
pattern.translate(position["x"], position["y"])
self.pattern.stitches.extend(pattern.stitches)
```

However what do I have to do if also want to keep the colors of each patterns ?

**Comment by tatarize** [comment]
Seems reasonable enough. You need to do the same thing you did for stitches for the threads.

The colors are stored in the pattern.
`self.threadlist = []`

self.pattern.threadlist.extend(pattern.threadlist)

Should similarly do the trick.

---

The patterns have a `stitches` list a `threadlist` list and a dict called `extras` which is a bunch of metadata. Some formats write out things like name, author, copyright, comment, pictures of the embroidery stuff and this stuff gets tossed into extra. These aren't super important but it's worth knowing that your method there is saying the name of the pattern is the one stored in self.pattern().  Depends a bit on the version you're writing but it's something to keep in mind.

**Comment by styloInt** [comment]
Thanks for your answer. I just tried that but it does not work :/. The orginals patterns are in black but the results are in green. There must be something else we need to add.

**Comment by tatarize** [comment]
I think what's happening is that the merged block is combined into the same color. So the colorlist colors are then going to be off by 1.

Stitches
--ColorChange
Stitches
--End
Stitches
--ColorChange
Stitches
--End

When we take the END command and throw it away we actually get:

Stitches
--ColorChange
Stitches
More Stitches That Were a Different Color
--ColorChange
Stitches
--End

Toss on a COLOR_CHANGE after you destroy pick off the END or convert the END commands to colorchanges them.

`pattern.color_change()`

**Comment by tatarize** [comment]
Also worth noting, the PES writer will sometimes move a color to avoid writing two colors as the same. So sometimes using the same color again will, under some circumstances, move it a bit, because there's an issue with it not stopping when it's changing from one color to the same color. So it makes sure to give avoid that by insisting each color is unique and assigning it to the next furthest color when you reuse them PES.

If you actually needed the merged lists to reuse the same colors like in a multi-needle machine, you might actually have to assign them. Though I think it only happens for PESv1. I think in the later versions it lets you assign them to a threadlist and then the values are lookup numbers in the threadchart defined in the header.

There's a pretty advanced system for assigning specific threads to specific color blocks so if it came to that it'd still be pretty easy. You'd just tag on some commands to force the assignments.

`thread.add_command(encode_thread_change(SET_CHANGE_SEQUENCE, thread=1, order=0))`

Which would force thread 1 in the threadlist[1] to be the first thread used. And you can assign them like that however you need. Hopefully it won't come to that.

**Comment by styloInt** [comment]
Thanks for your explanations. I managed to understand the issue thanks to that. 

I had to do : 
```
if len(self.pattern.threadlist) != 0\
    and (len(pattern.threadlist) > 0\
    and pattern.threadlist[0].color == self.pattern.threadlist[-1].color):
    pattern.threadlist = []
elif len(self.pattern.threadlist) != 0:
    self.pattern.color_change()

self.pattern.threadlist.extend(pattern.threadlist)
```

I think we can close this issue now. Or maybe you want it open in case you want to have a straight forward solution for merging patterns in the future ?

**Comment by tatarize** [comment]
I'll close it in a bit. I do need to likely update some documentation.

>> Or maybe you want it open in case you want to have a straight forward solution for merging patterns in the future ?

Can I have your code for that purpose?

Seem like pattern.merge(pattern) would be a fine function, especially since it's a harder problem than I gave it credit for when you asked. 

I'd would explicitly check if that last command is actually an END. I can't be sure somebody didn't write their own function, returned that data without and END command (which is perfectly valid), and I'd be clipping something else off erroneously. 

And I would toss in self.pattern.extras.update(pattern.extras) command to merge the metadata.

**Comment by styloInt** [comment]
Of coure you can use my code. here my final function (I didn't test it for all cases ...) :

```
    def _merge_pattern(self, pattern):
        pattern.stitches = pattern.stitches[:-1]  # Remvove END command

        # Add the new thread only if it's different from the last one
        if len(self.pattern.threadlist) != 0\
            and (len(pattern.threadlist) > 0 and
                 pattern.threadlist[0].color == self.pattern.threadlist[-1].color):

            pattern.threadlist = pattern.threadlist[1:]
            if len(pattern.threadlist) > 0:
                self.pattern.color_change()

        elif len(pattern.threadlist) != 0 and len(self.pattern.threadlist) != 0:
            self.pattern.color_change()

        self.pattern.threadlist.extend(pattern.threadlist)
        self.pattern.stitches.extend(pattern.stitches) 
```
