### ISSUE TITLE
Test files not included

### ISSUE THREAD

**Issue by JaredPhelps** [EmbroidePy/pyembroidery#93]
Hello - This is a question more than an issue - I'm new to python and interested in learning  embroidery formats. I thought a good way for me to better understand both would be to debug through the tests in this project, but it doesn't seem like the test files are included. Am I missing them, or can I download them from somewhere?

Thanks!
Jared

**Comment by tatarize** [comment]
The testing here is pretty robust but mostly intended to prove and keep the functionality of things on the up-and-up so changes don't break things. They don't however, contain a large number of preassembled filed. They tend to produce them dynamically, saving them, loading them, and converting them. Reloading them and tweaking them in different ways.

---

There is the `samples` project where I took some very basic files and saved identical files with a lot of different proprietary programs in a bunch of different formats.

https://github.com/EmbroidePy/samples

That should have a bunch of file samples for what other software writes. 

---

I also write a pretty significant amount of documentation on various formats and how they work 

https://edutechwiki.unige.ch/en/Embroidery_format

And all the different formats are laid out in a pretty deliberate effort to make them comprehesable if you're debugging through the loading of a file.

---

I usually just used mass-convert.py and load a bunch of files into a convert directory and have a results directory and debug all the work it does when doing all the conversion stuff.  Since it's gotta load all the files I put in `./convert` and makes every file type it can write for `./results`

https://github.com/EmbroidePy/pyembroidery-CLI/blob/master/mass_convert.py

**Comment by JaredPhelps** [comment]
Thank you, that's exactly what I was looking for!
